/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.5/samples
 */

plugins {
    id("java")
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

group = "com.cupoftea"
version = "1.3.5-SNAPSHOT"

repositories {
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://repo.aikar.co/content/groups/aikar/")
}

dependencies {
    compileOnly("com.destroystokyo.paper:paper-api:1.13.2-R0.1-SNAPSHOT")
    implementation("net.dv8tion:JDA:5.0.0-beta.13")
    implementation("co.aikar:acf-paper:0.5.1-SNAPSHOT")
    implementation("org.mongodb:mongodb-driver-sync:4.9.1")
}

tasks {
    shadowJar {
        archiveBaseName.set("DiscordMC")
        archiveClassifier.set("")
        relocate("co.aikar.commands", "com.cupoftea.discordmc.acf")
        relocate("co.aikar.locales", "com.cupoftea.discordmc.locales")
    }
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(8))
}
