/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.5/samples
 */

plugins {
    kotlin("jvm") version "1.9.22"
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("xyz.jpenilla.run-paper") version "2.2.2"
}

group = "com.cupoftea"
version = "1.3.5-SNAPSHOT"

repositories {
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://oss.sonatype.org/content/groups/public/")
}

dependencies {
    // Kotlin
    implementation(kotlin("stdlib"))
    implementation(kotlin("reflect"))
    
    // Paper API
    compileOnly("io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT")
    
    // Adventure & MiniMessage
    implementation("net.kyori:adventure-api:4.14.0")
    implementation("net.kyori:adventure-text-minimessage:4.14.0")
    
    // Discord
    implementation("net.dv8tion:JDA:5.0.0-beta.20")
    
    // Cloud Command Framework
    implementation("cloud.commandframework:cloud-paper:1.8.4")
    implementation("cloud.commandframework:cloud-annotations:1.8.4")
    implementation("cloud.commandframework:cloud-kotlin-extensions:1.8.4")
    implementation("cloud.commandframework:cloud-kotlin-coroutines:1.8.4")
    implementation("cloud.commandframework:cloud-kotlin-coroutines-annotations:1.8.4")
    
    // MongoDB
    implementation("org.mongodb:mongodb-driver-sync:4.11.1")
    
    // Coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
}

tasks {
    build {
        dependsOn(shadowJar)
    }
    
    shadowJar {
        archiveBaseName.set("DiscordMC")
        archiveClassifier.set("")
        
        // Relocate dependencies to avoid conflicts
        relocate("cloud.commandframework", "com.cupoftea.discordmc.libs.cloud")
        relocate("io.leangen.geantyref", "com.cupoftea.discordmc.libs.typetoken")
        
        // Ensure shadowJar runs after jar
        dependsOn(jar)
    }
    
    compileKotlin {
        kotlinOptions {
            jvmTarget = "17"
            freeCompilerArgs += "-Xjvm-default=all"
        }
    }
    
    jar {
        // Ensure the jar task runs after compilation
        dependsOn(compileKotlin)
    }
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}
