discord-bot-token: "YOUR_DISCORD_BOT_TOKEN"
discord-channel-id: "YOUR_DISCORD_CHANNEL_ID"
mongodb-connection-string: "mongodb://localhost:27017"
mongodb-database-name: "discordmc"
linked-account-role-id: ""  # Leave empty to create a default role