name: DiscordMC
version: '${version}'
main: com.cupoftea.discordmc.DiscordMCPlugin
api-version: '1.20.4'
authors: [cupoftea]
description: A plugin that bridges Minecraft and Discord chat

config-files:
  - messages.yml